repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        files: \.py$
      - id: end-of-file-fixer
        files: \.py$
      - id: check-yaml
      - id: check-added-large-files
        files: \.py$
        
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        files: \.py$
